apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
        name: other
  resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
