apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
    - name: workdir
      emptyDir:
        sizeLimit: "10Mi"
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600;
    image: busybox
    name: busybox
    volumeMounts:
    - name: workdir
      mountPath: /etc/foo
  - command:
    - /bin/sh
    - -c
    - sleep 3600;
    image: busybox
    name: busybox2
    volumeMounts:
    - name: workdir
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
