apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: limitrange
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "1250M"
        cpu: "500m"
      limits:
        memory: "1500M"
        cpu: "750m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
