apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    resources: {}
    volumeMounts:
    - name: username
      mountPath: /etc/foo
  volumes:
  - name: username
    secret:
      secretName: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
