apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-secret-env
  name: nginx-secret-env
spec:
  containers:
  - image: nginx
    name: nginx-secret-env
    resources: {}
    volumeMounts:
    - name: username
      mountPath: /etc/foo
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: creds
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: creds
          key: password
  volumes:
  - name: username
    secret:
      secretName: creds
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
