apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: secret-ops
spec:
  volumes:
  - name: skey
    secret:
      secretName: skey
      optional: true
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: skey
      mountPath: /var/app 
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
