apiVersion: batch/v1
kind: Job
metadata:
  name: one
spec:
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello; sleep 5; echo world;
        image: busybox
        name: five
        resources: {}
      restartPolicy: Never
status: {}
