apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: workdir
          mountPath: "/usr/share/nginx/html"
        resources: {}
      initContainers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - "echo version-1 > /work-dir/index.html"
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {} 
status: {}
