apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-tolerated
  name: nginx-tolerated
spec:
  containers:
  - image: nginx
    name: nginx-tolerated
    resources: {}
  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "frontend"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
